### ISSUE TITLE
Everytime I execute a command it gives me this error 

### ISSUE THREAD

**Issue by DomasSakalauskas** [Siebrenvde/StaffChat#1]
Everytime I use the command I get this error: 
![image](https://user-images.githubusercontent.com/41291632/79694540-bdc16800-8268-11ea-814e-7dbbaf40d968.png)

This also happens with reporting. I have followed the instructions and stopped the server and started it and still nothing this keeps happening

**Comment by Siebrenvde** [comment]
Fixed in 1.4.2
